name: Automerge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:          
      - name: automerge
              uses: ahmadnassri/action-automerge@v1
              with:
                github-token: "${{ secrets.MY_GITHUB_TOKEN }}"
